AppDjango/AppDjango/urls.py
from django.contrib import admin
from django.urls import path
from loginAdmin import views as loginadmin_views
from torneo import views as torneo_views
from jugador import views as jugador_views

urlpatterns = [
    path('admin/', admin.site.urls),    
    # URLs para la app 
    path('login/', loginadmin_views.admin_login, name='login'),
    path('admin_menu/', loginadmin_views.admin_menu, name='admin_menu'),    
    path('jugador/<str:dni>/', jugador_views.datos_jugador, name='listado_jugador'),  # Cambiado a dni
    path('menu/', loginadmin_views.menu, name='menu'),
    path('', torneo_views.index, name='index'),
    path('admin_carga_jugador/', jugador_views.CrearJugador, name='admin_carga_jugador'),
    path('guardar_jugador/', jugador_views.guardar_jugador, name='guardar_jugador'),
    path('listado_jugadores/', jugador_views.listado_jugadores, name='listado_jugadores'),
    path('abm_categoria/', jugador_views.abm_categoria, name='abm_categoria'),
    path('datos_jugador/<str:dni>/', jugador_views.datos_jugador, name='datos_jugador'),  # Este está correcto
    path('jugadores/', jugador_views.listado_categorias, name='listados_categorias'),
    path('exito_categoria/', jugador_views.exito_categoria, name='exito_categoria'),
    path('categorias/eliminar/<int:id_categoria>/', jugador_views.eliminar_categoria, name='eliminar_categoria'),
    path('borrado_exitoso/<str:jugador_dni>/', jugador_views.borrado_exitoso, name='borrado_exitoso'),  # Cambiado a str
    path('modificar_jugador/<str:dni>/', jugador_views.modificar_jugador, name='modificar_jugador'),
    path('borrar_jugador/<str:dni>/', jugador_views.borrar_jugador, name='borrar_jugador'),
    


]

AppDjango/jugador/models.py
from django.db import models

class Categoria(models.Model):
    id_categoria = models.AutoField(primary_key=True)
    nivel = models.IntegerField(default=0)  # Nuevo campo para Nivel
    edad = models.IntegerField(default=0)              # Nuevo campo para Edad
    tipo_juego = models.CharField(max_length=20,default='Sin tipo')  # Nuevo campo para Tipo de Juego

    def __str__(self):
        return f"Categoria: {self.nivel}+{self.edad}+{self.tipo_juego}"

class Jugador(models.Model):
    dni = models.CharField(max_length=8, primary_key=True)
    nombre = models.CharField(max_length=100)
    apellido = models.CharField(max_length=100)
    sexo = models.CharField(max_length=1)
    categorias = models.ManyToManyField(Categoria, through='JugadorCategoria')

    def __str__(self):
        return f"{self.nombre} {self.apellido}"

class JugadorCategoria(models.Model):
    jugador = models.ForeignKey(Jugador, on_delete=models.CASCADE)
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)

    class Meta:
        unique_together = ('jugador', 'categoria')

AppDjango/templates/abm_categoria.html
{% extends "layout.html" %}    
{% block body_class %}fondo-secundario{% endblock %}

{% block content %} 
<div class="container-admin">
    <h4>ADMINISTRADOR</h4>
    <div class="text-section">
        <hr class="separator-line"> <!-- Línea separadora -->
        <h2>ALTA</h2>
    </div>
    <div class="text-section">
        <hr class="separator-line"> <!-- Línea separadora -->
        <h5>CATEGORIA</h5>
    </div>
    <div class="form-container">
        <!-- Rectángulo angosto a la izquierda -->
        <div class="narrow-box">
            <div class="title-orange-gris">
                <h1>CATEGORIA</h1>
                <h3 class="negro chico">OPCIONES</h3>
            </div>
            <!--<br><br>
            <h3 class="negro">BUSCAR</h3>
            <hr class="separator">
            <input type="text" placeholder="Buscar por NOMBRE" class="input-field"><br>-->
            <br>
            <a href="{% url 'listados_categorias' %}">
                <button class="login-button chico">Listado completo</button>
            </a>
            <hr class="separator">
            <a href="{% url 'admin_menu' %}">
                <button class="login-button peque">MENU</button>
            </a>
            <hr class="separator">
            <!-- Contenedor para los botones -->
            <div class="buttons-container">
                <a href="{% url 'admin_menu' %}">
                    <button class="login-button-gris chico">IMPRIMIR</button>
                </a>
                <!--<a href="{% url 'admin_menu' %}">
                    <button class="login-button-gris chico">PDF</button>
                </a>-->
            </div>
        </div>

        <!-- Login box a la derecha del rectángulo angosto -->
        <div class="login-box">
            <form method="POST" action="{% url 'abm_categoria' %}" id="form-nuevo-jugador">
                
                    <div class="title-orange-box grande">
                        <h2>ALTA</h2>
                     </div>
                
                
                {% csrf_token %}
                <!-- Begin-22/09/2024- Franco Corbalan - Agrego tres input para agregar Nivel,Edad,Tipo de Juego, Se comenta descripcion -->
                <!--<div>
                    <br>
                    <label for="nombre">Descripcion</label>
                    <input type="text" id="nombre" name="nombre" placeholder="Descripcion" required>
                </div>-->
        
                <div>
                    <br>
                    <label for="nivel">Nivel</label>
                    <input type="text" id="nivel" name="nivel" placeholder="Nivel" required>
                </div>

                <div>
                    <br>
                    <label for="edad">Edad</label>
                    <input type="number" id="edad" name="edad" placeholder="Edad" required>
                </div> 

                <div>
                    <br>
                    <label for="tipo_juego">Tipo de Juego</label>
                    <select id="tipo_juego" name="tipo_juego" required>
                        <option value="" disabled selected>Seleccione un tipo de juego</option>
                        <option value="Single">Single</option>
                        <option value="Doble">Doble</option>
                        <option value="Mixto">Mixto</option>
                    </select>
                </div>                 
                <br>
                <button class="login-button" type="submit">Guardar</button>
                <!-- End-22/09/2024- Franco Corbalan - Agrego tres input para agregar Nivel,Edad,Tipo de Juego, Se comenta descripcion y se modifico tambien boton sigueintes
                 por guardar-->
            </form>
        </div>
    </div>
</div>
{% endblock %}

AppDjango/templates/admin_carga_jugador.html
{% extends "layout.html" %}    
{% block body_class %}fondo-secundario{% endblock %}

{% block content %} 
<div class="container-admin">
    <h4>ADMINISTRADOR</h4>
    <div class="text-section">
        <hr class="separator-line"> <!-- Línea separadora -->
        <h2>ALTA</h2>
    </div>
    <div class="text-section">
        <hr class="separator-line"> <!-- Línea separadora -->
        <h5>CARGA DE NUEVO JUGADOR</h5>
    </div>
    <div class="form-container">
        <!-- Rectángulo angosto a la izquierda -->
        <div class="narrow-box">
            <div class="title-orange-gris">
                <h1>JUGADORES</h1>
                <h3 class="negro chico">OPCIONES</h3>
            </div>
            <a href="{% url 'admin_menu' %}">
                <button class="login-button peque">MENU</button>
            </a>
      
            <a href="{% url 'listado_jugadores' %}">
                <button class="login-button chico">Listado completo</button>
            </a>
            <a href="{% url 'listado_jugadores' %}">
                <button class="login-button chico">por Categoria</button>
            </a>
            <hr class="separator">
            <h3 class="negro">BUSCAR POR JUGADOR</h3>            
            <input type="text" placeholder="Buscar por APELLIDO" class="input-field"><br>
            <hr class="separator"> 
            <a href="{% url 'admin_carga_jugador' %}">
                <button class="login-button chico">ALTA</button>
            </a>
            <hr class="separator">
                       
            <!-- Contenedor para los botones -->
            <div class="buttons-container">
                <a href="{% url 'admin_menu' %}">
                    <button class="login-button-gris chico">IMPRIMIR</button>
                </a>
                <a href="{% url 'admin_menu' %}">
                    <button class="login-button-gris chico">PDF</button>
                </a>
            </div>
        </div>

        <!-- Login box a la derecha del rectángulo angosto -->
        <div class="login-box">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button class="login-button" type="submit">SIGUIENTE</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

AppDjango/templates/admin_datos_jugador.html
{% extends "layout.html" %}    
{% load static %}

{% block content %} 
<div>
    <div class="title-bar">
        <h2>DATOS JUGADOR</h2>
    </div>
    <main>
        <section class="player-info">
            <div class="player-card">
                <div class="player-photo">
                    
                </div>
                <div class="player-details">
                    <div class="player-name">
                        <img src="{% static 'imagenes/pelota.png' %}" alt="Pelota">
                        <h3>Apellido</h3>
                        <h3>Nombre</h3>
                    </div>
                    <div class="player-data">
                        <p class="texto-gris"><strong>Datos</strong></p>
                        <hr>
                        <p>DNI: ########</p>
                        <p>Edad: ##</p>
                        <p>Ciudad: #######</p>
                    </div>
                    
                </div>
                <div class="player-stats">
                    <h1>TORNEO</h1>
                    <div class="stat">
                        <p class="texto-naranja">Single Hombres</p>
                        <div class="contenedor">
                            <p class="texto-gris">Categoría:  <span class="numero">###4° + 30</span></p>
                            <p class="texto-gris">Puntos: <span class="numero">#1500</span></p>
                            <p class="texto-gris">Posición: <span class="numero">#3°</span></p>
                        </div>
                    </div>
                    
                    <div class="stat">
                        <p class="texto-naranja">Doble Hombres</p>
                        <div class="contenedor">
                            <p class="texto-gris">Categoría: <span class="numero">###4° + 30</span></p>
                            <p class="texto-gris">Puntos: <span class="numero">###1500</span></p>
                            <p class="texto-gris">Posición: <span class="numero">###3°</span></p>
                        </div>
                    </div>
                </div>
            </div>
        </section >

       
        <p class="p-centrado"><strong>HISTORIAL</strong></p> 
        <section class="history">                     
                          
            <div class="history-item">
                <div class="player-data">
                    <p class="texto-naranja"><strong>Categoria</strong></p>
                    <hr>
                    <p class="texto-negro">##anterior Single Hombres</p>
                </div>     
                <div class="player-data">
                    <p class="texto-naranja"><strong>Posicion</strong></p>
                    <hr>
                    <p class="texto-negro">##anterior</p>
                </div>             
            </div>
            <div class="history-item">
                <div class="player-data">
                    <p class="texto-naranja"><strong>Categoria</strong></p>
                    <hr>
                    <p class="texto-negro">##anterior Single Hombres</p>
                </div>     
                <div class="player-data">
                    <p class="texto-naranja"><strong>Posicion</strong></p>
                    <hr>
                    <p class="texto-negro">##anterior</p>
                </div>             
            </div>
        </section>
        <p class="p-centrado"><strong>PARTIDOS JUGADOS</strong></p>

        <section class="match-history">        
            <div class="match">
                <p>Franco Corva 6 3 6</p>
                <p>Tomas Servan 2 6 1</p>
            </div>
            <div class="match">
                <p>Juan Perez 7 5 6</p>
                <p>Pedro Lopez 3 7 2</p>
            </div>
            <div class="match">
                <p>Diego Marquez 6 4 6</p>
                <p>Carlos Ruiz 1 6 3</p>
            </div>
        </section>
        

        <div class="actions">
            <button class="login-button">MODIFICAR</button>
            <button class="login-button">BORRAR</button>
        </div>
    </main>
</div>
{% endblock %}

AppDjango/templates/admin_login.html
{% extends "layout.html" %}

{% block content %}
<!-- Barra de Título -->
<div class="container-admin">
    <h4>ADMINISTRADOR </h4>
    <div class="text-section">
        <hr class="separator-line"> <!-- Línea separadora -->
        <p>LOGIN PARA USUARIO PERMITIDO</p>
    </div>
    <div>
        <div class="login-box">
            <h3>USUARIO </h3>
            <input type="text" placeholder="Usuario" class="input-field">
            <hr class="separator">
            <h3>CLAVE </h3>
            <input type="password" placeholder="Clave" class="input-field">
            <div class="remember-me">
                <input type="checkbox" id="remember">
                <label for="remember" class="remember-me-label">Recordar</label>
            </div>
            <!-- template.html -->
            <a href="{% url 'admin_menu' %}">
                <button class="login-button">Aceptar</button>
            </a>
        </div>
    </div>
</div>
{% endblock %}

AppDjango/templates/borrado_exitoso.html
{% extends "layout.html" %}

{% block content %}
<div class="confirmation-message">
    <h4>El dato ha sido ELIMINADO</h4>
    <a href="{% url 'listado_jugadores' %}" class="login-button">Volver al listado </a>  <!-- Cambiado a 'listado_jugadores' -->
</div>
{% endblock %}

AppDjango/templates/error_page.html
{% extends "layout.html" %}

{% block content %}

<head>
    <title>Error</title>
</head>

    <h1>¡Ocurrió un error!</h1>
    <p>{{ error }}</p>


{% endblock %}

AppDjango/templates/exito_categoria.html
{% extends "layout.html" %}

{% block content %}
<div class="container-admin">
    <h4>Categoría Creada</h4>
    <p>La categoría se ha creado exitosamente.</p>
    <a href="{% url 'admin_menu' %}" class="login-button">Volver al menu</a>
</div>
{% endblock %}

AppDjango/templates/guardar_jugador.html
{% extends "layout.html" %}
{% block body_class %}fondo-secundario{% endblock %}

{% block content %}
<div class="container-admin">
    <h2>Operación Exitosa</h2>
    <p>El jugador ha sido guardado exitosamente.</p>
    <a href="{% url 'admin_menu' %}" class="login-button">Ir al Menú Principal</a>
</div>
{% endblock %}

AppDjango/templates/index.html
{% extends "layout.html" %}

{% load static %}  <!-- Asegúrate de cargar el módulo estático -->

{% block content %}
<div class="container-admin">
    <h4>GESTOR DE TORNEOS</h4>
    <div class="text-section">
        <hr class="separator-line"> <!-- Línea separadora -->
        <p>ONN</p>
    </div>
    <div>
        <img src="{% static 'imagenes/logo apur.png' %}" alt="Logo"/>
    </div>
</div>
{% endblock %}

AppDjango/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        !Liga Tenis 2024
        {% block title %}
        {% endblock %}
    </title>
   <!-- Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/5.1.3/css/bootstrap.min.css" rel="stylesheet">

    <!-- Bootstrap Icons -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Libre+Bodoni&family=Roboto:wght@100;300;400;500;700;900&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@200..700&display=swap" rel="stylesheet">

    <!-- jQuery (opcional, solo si es necesario) -->
    <!-- JS de Bootstrap y dependencias (jQuery y Popper.js) -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js"></script>

    <!-- Bootstrap JS -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.1.3/js/bootstrap.bundle.min.js" defer></script>

    <!-- Estilos personalizados -->
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">

    <!-- Script personalizado -->
    <script src="{% static 'js/script.js' %}" defer></script>


</head>
<body class="{% block body_class %}fondo-principal{% endblock %}">
    <header>
        <div class="menu-principal">
            <button class="hamburguesa" id="menu-toggle">≡</button> <!-- Botón de menú a la izquierda -->
            
            <ul class="nav-list">
                <li class="nav-item">
                    <a class="nav-link" href="#">PADRON</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">TORNEOS</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">CATEGORIAS</a>
                </li>
            </ul>
            <a href="{% url 'login' %}">
                <img src="{% static 'imagenes/logo apur.png' %}" alt="APUR Logo" class="logo-menu"> <!-- Logo a la derecha -->
            </a>
        </div>

        <div class="side-menu" id="side-menu">
            <div class="menu-header">
                <h2>ONN</h2>
                <span class="close-btn" id="close-btn">&times;</span>
            </div>
            <ul>
                <li ><a href="genero.html">RANKING</a></li>
                <hr class="separator-negro">
                <li><a href="#">CATEGORIAS</a></li>
                <hr class="separator-negro">
                <li><a href="{% url 'admin_menu' %}">JUGADORES</a></li>
                <hr class="separator-negro">
                <li><a href="#">TIENDA</a></li>
                <hr class="separator-negro">
            </ul>
            <ul>
                <li><a href="#" class="contact-link">Políticas de seguridad</a></li>
                <li><a href="#" class="contact-link">Notificar problemas</a></li>
                <hr class="separator-negro">
                <li><a href="https://wa.me/+5493413006495" class="contact-link">CONTACTO</a></li>
            </ul>
        </div>
    </header>
    
    <div id="content"> 
        {% block content %}
        <!-- Aquí va el código de cada página del template -->
        {% endblock %}
    </div>

    <footer>
        <div class="footer-bar">
            <a href="{% url 'index' %}" class="home-link">
                <button class="icon-button">
                    <i class="bi bi-house-door-fill"></i><!-- Icono de home -->
                </button>
            </a>
            <button class="footer-button">SALIR</button>
            <button class="icon-button" id="back-btn">
                <i class="bi bi-backspace-fill"></i>
            </button>
        </div>
    </footer>
</body>
</html>

AppDjango/templates/listado_jugadores.html
{% extends "layout.html" %}
{% block body_class %}fondo-secundario{% endblock %}

{% block content %}
<div class="container-admin">
    <h4>ADMINISTRADOR</h4>
    <div class="text-section">
        <hr class="separator-line">
        <h2>LISTADO</h2>
    </div>
    <div class="text-section">
        <hr class="separator-line">
        <h5>COMPLETO DE JUGADORES</h5>
    </div>
    <div class="form-container">
        <div class="narrow-box">
            <div class="title-orange-gris">
                <h1>JUGADORES</h1>
                <h3 class="negro chico">OPCIONES</h3>
            </div>
            <a href="{% url 'admin_menu' %}">
                <button class="login-button peque">MENU</button>
            </a>
            <a href="{% url 'listado_jugadores' %}">
                <button class="login-button chico">Listado completo</button>
            </a>
            <a href="{% url 'listado_jugadores' %}">
                <button class="login-button chico">Por Categoría</button>
            </a>
            <hr class="separator">
            <h3 class="negro">BUSCAR POR JUGADOR</h3>
            <form method="GET" action="{% url 'listado_jugadores' %}" class="d-flex align-items-center mb-3">
                <input class="input-field" type="text" name="search" placeholder="Buscar por nombre o apellido" value="{{ search }}">
                <button class="login-button-gris chico ms-2" type="submit">Buscar</button>
            </form>
            <hr class="separator">
            <a href="{% url 'admin_carga_jugador' %}">
                <button class="login-button chico">ALTA</button>
            </a>
            <hr class="separator">
          
            <div class="buttons-container">
                <a href="{% url 'admin_menu' %}">
                    <button class="login-button-gris chico">IMPRIMIR</button>
                </a>
                <a href="{% url 'admin_menu' %}">
                    <button class="login-button-gris chico">PDF</button>
                </a>
            </div>
        </div>

        <div class="login-box listados">
            <!-- Nueva barra de color que contiene la paginación y el filtro -->
            <div class="barra-titulo">
                <div class="barra-titulo-contenido d-flex justify-content-between align-items-center">
                    <!-- Paginación -->
                    <div class="pagination d-flex align-items-center">
                        <div class="fw-bold mx-3">
                            Página {{ jugadores.number }} de {{ jugadores.paginator.num_pages }}&nbsp;&nbsp;
                        </div>
                        <div class="d-flex me-3">
                            {% if jugadores.has_previous %}
                                <a href="?page={{ jugadores.previous_page_number }}" class="login-button peque">&lt;</a>
                            {% endif %}
                        </div>
                        <div class="d-flex">
                            {% if jugadores.has_next %}
                                <a href="?page={{ jugadores.next_page_number }}" class="login-button peque">&gt;</a>
                            {% endif %}
                        </div>
                    </div>

                    <!-- Formulario de filtrado por sexo -->
                    <form method="GET" action="{% url 'listado_jugadores' %}" class="d-flex align-items-center ms-3">
                        <select name="sexo" class="input-field me-2" style="width: 200px;" onchange="this.form.submit()">
                            <option value="">Filtrar por sexo</option>
                            <option value="masculino" {% if sexo == "masculino" %} selected {% endif %}>Masculino</option>
                            <option value="femenino" {% if sexo == "femenino" %} selected {% endif %}>Femenino</option>
                        </select>
                        <input type="hidden" name="search" value="{{ search }}">
                    </form>
                </div>
            </div>
            <!-- Fin de la nueva barra -->

            <table class="table table-striped-columns table-light table-bordered table-sm">
                <thead class="table-success">
                    <tr class="title-container">
                        <th>APELLIDO</th>
                        <th>NOMBRE</th>
                        <th>DNI</th>
                        <th>SEXO</th>
                        <th>CATEGORÍA</th>
                        <th>INFO</th>
                        <th>MODIFICAR</th>
                        <th>ELIMINAR</th>
                    </tr>
                </thead>
                <tbody>
                    {% if jugadores %}
                        {% for jugador in jugadores %}
                            <tr>
                                <th scope="row">{{ jugador.apellido }}</th>
                                <td>{{ jugador.nombre }}</td>
                                <td>{{ jugador.dni }}</td>
                                <td>{{ jugador.sexo }}</td>
                                <td>
                                    {% for jugador_categoria in jugador.jugadorcategoria_set.all %}
                                        {{ jugador_categoria.categoria.nivel }} - {{ jugador_categoria.categoria.edad }} - {{ jugador_categoria.categoria.tipo_juego }}
                                        s{% if not forloop.last %}, {% endif %}
                                    {% endfor %}
                                </td>
                                <td>
                                    <a href="{% url 'datos_jugador' jugador.dni %}" class="modificar-button">+</a>
                                </td>
                                <td>
                                    <button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#modificarModal-{{ jugador.dni }}">
                                        <i class="bi bi-pencil-square"></i>
                                    </button>
                                    <!-- Modal para modificar el jugador -->
                                    <div class="modal fade" id="modificarModal-{{ jugador.dni }}" tabindex="-1" aria-labelledby="modificarModalLabel-{{ jugador.dni }}" aria-hidden="true">
                                        <div class="modal-dialog">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h3 class="modal-title" id="modificarModalLabel-{{ jugador.dni }}">Modificar jugador '{{ jugador.apellido }} {{ jugador.nombre }}'</h3>
                                                    <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                                                        <i class="bi bi-x" style="font-size: 1.5rem;"></i>
                                                    </button>
                                                </div>
                                                <div class="modal-body">
                                                    <form method="POST" action="{% url 'modificar_jugador' jugador.dni %}">
                                                        {% csrf_token %}
                                                        <div class="mb-3">
                                                            <label for="nombre">Nombre:</label>
                                                            <input class="input-field" type="text" value="{{ jugador.nombre }}" name="nombre" id="nombre" class="form-control" required>
                                                        </div>
                                                        <div class="mb-3">
                                                            <label for="apellido">Apellido:</label>
                                                            <input class="input-field" type="text" value="{{ jugador.apellido }}" name="apellido" id="apellido" class="form-control" required>
                                                        </div>
                                                        <div class="mb-3">
                                                            <label for="dni">DNI:</label>
                                                            <input class="input-field" type="text" value="{{ jugador.dni }}" name="dni" id="dni" class="form-control" required>
                                                        </div>
                                                        <div class="mb-3">
                                                            <label for="sexo">Sexo:</label>
                                                            <select class="form-select" name="sexo" id="sexo" required>
                                                                <option value="M" {% if jugador.sexo == "M" %} selected {% endif %}>Masculino</option>
                                                                <option value="F" {% if jugador.sexo == "F" %} selected {% endif %}>Femenino</option>
                                                            </select>
                                                        </div>
                                                        <div class="text-center">
                                                            <button class="login-button">Guardar cambios</button>
                                                        </div>
                                                    </form>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </td>
                                <td>
                                    <!-- Botón BORRAR con clase 'delete-button' -->
                                    <button class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#eliminarModal-{{ jugador.dni }}">
                                        <i class="bi bi-trash-fill"></i>
                                    </button>
                                    {% include 'modal_eliminar_jugador.html' %}
                                </td>
                            </tr>
                        {% endfor %}
                    {% else %}
                        <tr>
                            <td colspan="8" class="text-center">No hay jugadores registrados.</td>
                        </tr>
                    {% endif %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

AppDjango/templates/modal_eliminar_jugador.html
<!-- Modal para eliminar jugador -->
<div class="modal fade" id="eliminarModal-{{ jugador.dni }}" tabindex="-1" aria-labelledby="eliminarModalLabel-{{ jugador.dni }}" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h3 id="eliminarModalLabel-{{ jugador.dni }}">¿Está seguro desea eliminar al jugador {{ jugador.apellido }} {{ jugador.nombre }}???</h3>
                <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                    <i class="bi bi-x" style="font-size: 1.5rem;"></i>
                </button>
            </div>
            <div class="modal-body text-center">
                <a href="{% url 'borrar_jugador' jugador.dni %}" class="login-button rojo delete-button">Eliminar Jugador</a>
            </div>
        </div>
    </div>
    <!-- Modal para eliminar jugador -->
</div>